// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=ts"
// @generated from file devkit/v1/devkit.proto (package devkit.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreatedResponse, Empty, LoginRequest, LoginResponse, PingResponse, RegisterRequest } from "./devkit_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service devkit.v1.DevkitService
 */
export const DevkitService = {
  typeName: "devkit.v1.DevkitService",
  methods: {
    /**
     * @generated from rpc devkit.v1.DevkitService.Ping
     */
    ping: {
      name: "Ping",
      I: Empty,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Auth
     * Auth Mutation
     *
     * @generated from rpc devkit.v1.DevkitService.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc devkit.v1.DevkitService.Register
     */
    register: {
      name: "Register",
      I: RegisterRequest,
      O: CreatedResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

