// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package xsqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID        uuid.UUID
	Name      string
	Type      string
	Ext       string
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type OutboxItem struct {
	ID            string
	IdempotentKey string
	Version       int32
	Status        string
	JobType       string
	Payload       string
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	Role      string
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
