// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: user_management.write.sql

package xsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const saveUser = `-- name: SaveUser :one
INSERT INTO users (id, "name", email, "password", "role", active, created_at, updated_at) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET 
    "name" = EXCLUDED."name",
    email = EXCLUDED.email,
    "password" = EXCLUDED."password",
    "role" = EXCLUDED."role",
    active = EXCLUDED.active,
    created_at = EXCLUDED.created_at,
    updated_at = EXCLUDED.updated_at
RETURNING id
`

type SaveUserParams struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	Role      string
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, saveUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Role,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
